name: tobey

inheritsFrom:
  - ../.fabfile.yaml

hosts:
  ci:
    scripts:
      lint:tobey:
        context: docker-image
        image:  golangci/golangci-lint:v1.56.2 
        script:
          - export GOCACHE=/tmp && export GOLANGCI_LINT_CACHE=/tmp && golangci-lint run -v --timeout 600s

      test:tobey:
        context: docker-image
        image:  golang:1.22
        script:
          - export GOCACHE=/tmp  && go test .

      build:tobey:
        defaults:
          user: gitlab-ci-token
        script:
          - docker login -u %arguments.user% -p %secret.ci-build-token% %settings.gitlab.registry%
          - execute(script, build:service, --arguments service=tobey)
      push:tobey:
        script:
          - execute(script, push:service, --arguments service=tobey)
