apiVersion: v1
kind: Secret
metadata:
  name: tobey-secret
  labels:
    environment: {{ environment }}
    app: tobey-service
    type: backend
type: Opaque
stringData:
  TOBEY_DSN: "http://tobey:9010"
  TOBEY_RABBITMQ_DSN: "amqp://{{tobey.rabbitmq.user|raw}}:{{tobey.rabbitmq.pass|raw}}@{{tobey.rabbitmq.host|raw}}:5672/"
  TOBEY_REDIS_DSN: "redis:6379/0"
  TOBEY_PROGRESS_DSN: "http://progress"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger:4318/v1/traces"
  LOG_LEVEL: "ERROR"
  TOBEY_ENABLE_TRACING: "true"
  TOBEY_DEBUG: "false"